### ISSUE TITLE
could you teach me what part should i fixed ? i typed all with your code

### ISSUE THREAD

**Issue by useruniversity** [MarcusNg/flutter_youtube_api#3]
Project : Flutter youtube player  (your channel : https://www.youtube.com/watch?v=feQhHStBVLE)
I don't know coding , but like. follow your channel and want to make as U.
i typed all of coding with your screen. but it can't work. please teach me what part should i fixed ?

Launching lib/main.dart on sdk gphone x86 arm in debug mode...
Running Gradle task 'assembleDebug'...
Invalid depfile: /Users/suli/nopa_youtube/.dart_tool/flutter_build/387d647edd2b2a3b7bc8d61a586e7d0a/kernel_snapshot.d
Invalid depfile: /Users/suli/nopa_youtube/.dart_tool/flutter_build/387d647edd2b2a3b7bc8d61a586e7d0a/kernel_snapshot.d
lib/services/api_service.dart:2:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:657:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:825:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:572:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:43:22)
#5      starter (package:flutter_frontend_server/server.dart:182:27)
#6      main (file:///opt/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:9:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

FAILURE: Build failed with an exception.

* Where:
Script '/Users/suli/developer/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 904

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/suli/developer/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by sonu25r2e5** [comment]
so clean flutter clean or install new androdi emulator it might solved your problem
